on:
  schedule:
    - cron: '*10 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        run: curl -f https://climate-vyu.onrender.com/api/health